var MEL1 = { notes: [   // 터키 행진곡
        {pitch: 71, quantizedStartStep: 0, quantizedEndStep: 1},
        {pitch: 69, quantizedStartStep: 1, quantizedEndStep: 2},
        {pitch: 68, quantizedStartStep: 2, quantizedEndStep: 3},
        {pitch: 69, quantizedStartStep: 3, quantizedEndStep: 4},
        {pitch: 72, quantizedStartStep: 4, quantizedEndStep: 6},
        {pitch: 74, quantizedStartStep: 8, quantizedEndStep: 9},
        {pitch: 72, quantizedStartStep: 9, quantizedEndStep: 10},
        {pitch: 71, quantizedStartStep: 10, quantizedEndStep: 11},
        {pitch: 72, quantizedStartStep: 11, quantizedEndStep: 12},
        {pitch: 76, quantizedStartStep: 12, quantizedEndStep: 14}, //10
        {pitch: 77, quantizedStartStep: 16, quantizedEndStep: 17},
        {pitch: 76, quantizedStartStep: 17, quantizedEndStep: 18},
        {pitch: 75, quantizedStartStep: 18, quantizedEndStep: 19},
        {pitch: 76, quantizedStartStep: 19, quantizedEndStep: 20},
        {pitch: 83, quantizedStartStep: 20, quantizedEndStep: 21},
        {pitch: 81, quantizedStartStep: 21, quantizedEndStep: 22},
        {pitch: 80, quantizedStartStep: 22, quantizedEndStep: 23},
        {pitch: 81, quantizedStartStep: 23, quantizedEndStep: 24},
        {pitch: 83, quantizedStartStep: 24, quantizedEndStep: 25},
        {pitch: 81, quantizedStartStep: 25, quantizedEndStep: 26},
        {pitch: 80, quantizedStartStep: 26, quantizedEndStep: 27},
        {pitch: 81, quantizedStartStep: 27, quantizedEndStep: 28},
        {pitch: 84, quantizedStartStep: 28, quantizedEndStep: 30}

    ]};

var MEL11 = { notes: [
        {pitch: 57, quantizedStartStep: 4, quantizedEndStep: 6},
        {pitch: 60, quantizedStartStep: 6, quantizedEndStep: 8},
        {pitch: 60, quantizedStartStep: 8, quantizedEndStep: 10},
        {pitch: 60, quantizedStartStep: 10, quantizedEndStep: 12},
        {pitch: 57, quantizedStartStep: 12, quantizedEndStep: 14},
        {pitch: 60, quantizedStartStep: 14, quantizedEndStep: 16},
        {pitch: 60, quantizedStartStep: 16, quantizedEndStep: 18},
        {pitch: 60, quantizedStartStep: 18, quantizedEndStep: 20},
        {pitch: 57, quantizedStartStep: 20, quantizedEndStep: 22},
        {pitch: 60, quantizedStartStep: 22, quantizedEndStep: 24},
        {pitch: 57, quantizedStartStep: 24, quantizedEndStep: 26},
        {pitch: 60, quantizedStartStep: 26, quantizedEndStep: 28},
        {pitch: 57, quantizedStartStep: 28, quantizedEndStep: 30}
    ]};

var MEL2 = { notes: [ // 월광 소나타 3악장
        {pitch: 44, quantizedStartStep: 1, quantizedEndStep: 2},
        {pitch: 49, quantizedStartStep: 2, quantizedEndStep: 3},
        {pitch: 52, quantizedStartStep: 3, quantizedEndStep: 4},
        {pitch: 56, quantizedStartStep: 4, quantizedEndStep: 5},
        {pitch: 49, quantizedStartStep: 5, quantizedEndStep: 6},
        {pitch: 52, quantizedStartStep: 6, quantizedEndStep: 7},
        {pitch: 56, quantizedStartStep: 7, quantizedEndStep: 8},
        {pitch: 61, quantizedStartStep: 8, quantizedEndStep: 9},
        {pitch: 52, quantizedStartStep: 9, quantizedEndStep: 10},
        {pitch: 56, quantizedStartStep: 10, quantizedEndStep: 11},
        {pitch: 61, quantizedStartStep: 11, quantizedEndStep: 12},
        {pitch: 64, quantizedStartStep: 12, quantizedEndStep: 13},
        {pitch: 56, quantizedStartStep: 13, quantizedEndStep: 14},
        {pitch: 61, quantizedStartStep: 14, quantizedEndStep: 15},
        {pitch: 64, quantizedStartStep: 15, quantizedEndStep: 16},
        {pitch: 68, quantizedStartStep: 16, quantizedEndStep: 17},
        {pitch: 61, quantizedStartStep: 17, quantizedEndStep: 18},
        {pitch: 64, quantizedStartStep: 18, quantizedEndStep: 19},
        {pitch: 68, quantizedStartStep: 19, quantizedEndStep: 20},
        {pitch: 73, quantizedStartStep: 20, quantizedEndStep: 21},
        {pitch: 64, quantizedStartStep: 21, quantizedEndStep: 22},
        {pitch: 68, quantizedStartStep: 22, quantizedEndStep: 23},
        {pitch: 73, quantizedStartStep: 23, quantizedEndStep: 24},
        {pitch: 76, quantizedStartStep: 24, quantizedEndStep: 25},
        {pitch: 68, quantizedStartStep: 25, quantizedEndStep: 26},
        {pitch: 73, quantizedStartStep: 26, quantizedEndStep: 27},
        {pitch: 76, quantizedStartStep: 27, quantizedEndStep: 28}, //
        {pitch: 80, quantizedStartStep: 28, quantizedEndStep: 30},
        {pitch: 80, quantizedStartStep: 30, quantizedEndStep: 32},
    ]};

var MEL22 = { notes: [
        {pitch: 37, quantizedStartStep: 0, quantizedEndStep: 2},
        {pitch: 44, quantizedStartStep: 2, quantizedEndStep: 4},
        {pitch: 37, quantizedStartStep: 4, quantizedEndStep: 6},
        {pitch: 44, quantizedStartStep: 6, quantizedEndStep: 8},
        {pitch: 37, quantizedStartStep: 8, quantizedEndStep: 10},
        {pitch: 44, quantizedStartStep: 10, quantizedEndStep: 12},
        {pitch: 37, quantizedStartStep: 12, quantizedEndStep: 14},
        {pitch: 44, quantizedStartStep: 14, quantizedEndStep: 16},
        {pitch: 37, quantizedStartStep: 16, quantizedEndStep: 18},
        {pitch: 44, quantizedStartStep: 18, quantizedEndStep: 20},
        {pitch: 37, quantizedStartStep: 20, quantizedEndStep: 22},
        {pitch: 44, quantizedStartStep: 22, quantizedEndStep: 24},
        {pitch: 37, quantizedStartStep: 24, quantizedEndStep: 26},
        {pitch: 44, quantizedStartStep: 26, quantizedEndStep: 28},
        {pitch: 76, quantizedStartStep: 28, quantizedEndStep: 30},
        {pitch: 76, quantizedStartStep: 30, quantizedEndStep: 32},

    ]};

var MEL3 = { notes: [ // 엘리제를 위하여
        {pitch: 88, quantizedStartStep: 0, quantizedEndStep: 1},
        {pitch: 87, quantizedStartStep: 1, quantizedEndStep: 2},
        {pitch: 88, quantizedStartStep: 2, quantizedEndStep: 3},
        {pitch: 87, quantizedStartStep: 3, quantizedEndStep: 4},
        {pitch: 88, quantizedStartStep: 4, quantizedEndStep: 5},
        {pitch: 83, quantizedStartStep: 5, quantizedEndStep: 6},
        {pitch: 86, quantizedStartStep: 6, quantizedEndStep: 7},
        {pitch: 84, quantizedStartStep: 7, quantizedEndStep: 8},
        {pitch: 81, quantizedStartStep: 8, quantizedEndStep: 10},
        {pitch: 72, quantizedStartStep: 11, quantizedEndStep: 12},
        {pitch: 76, quantizedStartStep: 12, quantizedEndStep: 13},
        {pitch: 81, quantizedStartStep: 13, quantizedEndStep: 14},
        {pitch: 83, quantizedStartStep: 14, quantizedEndStep: 16},
        {pitch: 76, quantizedStartStep: 17, quantizedEndStep: 18},
        {pitch: 80, quantizedStartStep: 18, quantizedEndStep: 19},
        {pitch: 83, quantizedStartStep: 19, quantizedEndStep: 20},
        {pitch: 84, quantizedStartStep: 20, quantizedEndStep: 22},
        {pitch: 76, quantizedStartStep: 23, quantizedEndStep: 24},
        {pitch: 88, quantizedStartStep: 24, quantizedEndStep: 25},
        {pitch: 87, quantizedStartStep: 25, quantizedEndStep: 26},
        {pitch: 88, quantizedStartStep: 26, quantizedEndStep: 27},
        {pitch: 87, quantizedStartStep: 27, quantizedEndStep: 28},
        {pitch: 88, quantizedStartStep: 28, quantizedEndStep: 29},
        {pitch: 83, quantizedStartStep: 29, quantizedEndStep: 30},
        {pitch: 86, quantizedStartStep: 30, quantizedEndStep: 31},
        {pitch: 84, quantizedStartStep: 31, quantizedEndStep: 32},
        // {pitch: 81, quantizedStartStep: 32, quantizedEndStep: 34},
        // {pitch: 72, quantizedStartStep: 35, quantizedEndStep: 36},
        // {pitch: 76, quantizedStartStep: 36, quantizedEndStep: 37},
        // {pitch: 81, quantizedStartStep: 37, quantizedEndStep: 38},
        // {pitch: 83, quantizedStartStep: 38, quantizedEndStep: 40},
    ]};

var MEL33 = { notes: [
        {pitch: 57, quantizedStartStep: 8, quantizedEndStep: 9},
        {pitch: 64, quantizedStartStep: 9, quantizedEndStep: 10},
        {pitch: 69, quantizedStartStep: 10, quantizedEndStep: 11},
        {pitch: 52, quantizedStartStep: 14, quantizedEndStep: 15},
        {pitch: 64, quantizedStartStep: 15, quantizedEndStep: 16},
        {pitch: 68, quantizedStartStep: 16, quantizedEndStep: 17},
        {pitch: 57, quantizedStartStep: 20, quantizedEndStep: 21},
        {pitch: 64, quantizedStartStep: 21, quantizedEndStep: 22},
        {pitch: 69, quantizedStartStep: 22, quantizedEndStep: 23},
    ]};

var MEL4 = { notes: [    // 흑건
        // {pitch: 90, quantizedStartStep: 0, quantizedEndStep: 1},
        // {pitch: 94, quantizedStartStep: 1, quantizedEndStep: 2},
        // {pitch: 85, quantizedStartStep: 2, quantizedEndStep: 3},
        // {pitch: 90, quantizedStartStep: 3, quantizedEndStep: 4},
        // {pitch: 87, quantizedStartStep: 4, quantizedEndStep: 5},
        // {pitch: 90, quantizedStartStep: 5, quantizedEndStep: 6},
        // {pitch: 85, quantizedStartStep: 6, quantizedEndStep: 7},
        {pitch: 87, quantizedStartStep: 0, quantizedEndStep: 1},
        {pitch: 82, quantizedStartStep: 1, quantizedEndStep: 2},
        {pitch: 85, quantizedStartStep: 2, quantizedEndStep: 3},
        {pitch: 78, quantizedStartStep: 3, quantizedEndStep: 4},
        {pitch: 82, quantizedStartStep: 4, quantizedEndStep: 5},
        {pitch: 78, quantizedStartStep: 5, quantizedEndStep: 6},
        {pitch: 82, quantizedStartStep: 6, quantizedEndStep: 7},
        {pitch: 73, quantizedStartStep: 7, quantizedEndStep: 8},
        {pitch: 78, quantizedStartStep: 8, quantizedEndStep: 9},
        {pitch: 75, quantizedStartStep: 9, quantizedEndStep: 10},
        {pitch: 78, quantizedStartStep: 10, quantizedEndStep: 11},
        {pitch: 73, quantizedStartStep: 11, quantizedEndStep: 12},
        {pitch: 78, quantizedStartStep: 12, quantizedEndStep: 13},
        {pitch: 70, quantizedStartStep: 13, quantizedEndStep: 14},
        {pitch: 73, quantizedStartStep: 14, quantizedEndStep: 15},
        {pitch: 66, quantizedStartStep: 15, quantizedEndStep: 16},
        {pitch: 70, quantizedStartStep: 16, quantizedEndStep: 17},
        {pitch: 61, quantizedStartStep: 17, quantizedEndStep: 18},
        {pitch: 73, quantizedStartStep: 18, quantizedEndStep: 19},
        {pitch: 68 , quantizedStartStep: 19, quantizedEndStep: 20},
        {pitch: 75 , quantizedStartStep: 20, quantizedEndStep: 21},
        {pitch: 80 , quantizedStartStep: 21, quantizedEndStep: 22},
        {pitch: 75 , quantizedStartStep: 22, quantizedEndStep: 23},
        {pitch: 85, quantizedStartStep: 23, quantizedEndStep: 24},
        {pitch: 80, quantizedStartStep: 24, quantizedEndStep: 25},
        {pitch: 92, quantizedStartStep: 25, quantizedEndStep: 26},
        {pitch: 80, quantizedStartStep: 26, quantizedEndStep: 27},
        {pitch: 92, quantizedStartStep: 27, quantizedEndStep: 28},
        {pitch: 87, quantizedStartStep: 28, quantizedEndStep: 29},
        {pitch: 92, quantizedStartStep: 29, quantizedEndStep: 30},
        {pitch: 87, quantizedStartStep: 30, quantizedEndStep: 31},
        {pitch: 99, quantizedStartStep: 31, quantizedEndStep: 32},
    ]};

var MEL44 = { notes: [
        {pitch: 63, quantizedStartStep: 0, quantizedEndStep: 3},
        {pitch: 63, quantizedStartStep: 3, quantizedEndStep: 6},
        {pitch: 63, quantizedStartStep: 6, quantizedEndStep: 9},
        {pitch: 51, quantizedStartStep: 12, quantizedEndStep: 15},
        {pitch: 66, quantizedStartStep: 15, quantizedEndStep: 18},
        {pitch: 66, quantizedStartStep: 18, quantizedEndStep: 21},
        {pitch: 46, quantizedStartStep: 24, quantizedEndStep: 27},
        {pitch: 65, quantizedStartStep: 27, quantizedEndStep: 30},
        {pitch: 65, quantizedStartStep: 30, quantizedEndStep: 32},
    ]};

var MEL5 = { notes: [ // 왕벌의 비행
        {pitch: 88, quantizedStartStep: 0, quantizedEndStep: 1},
        {pitch: 87, quantizedStartStep: 1, quantizedEndStep: 2},
        {pitch: 86, quantizedStartStep: 2, quantizedEndStep: 3},
        {pitch: 85, quantizedStartStep: 3, quantizedEndStep: 4},
        {pitch: 86, quantizedStartStep: 4, quantizedEndStep: 5},
        {pitch: 85, quantizedStartStep: 5, quantizedEndStep: 6},
        {pitch: 84, quantizedStartStep: 6, quantizedEndStep: 7},
        {pitch: 83, quantizedStartStep: 7, quantizedEndStep: 8},
        {pitch: 84, quantizedStartStep: 8, quantizedEndStep: 9},
        {pitch: 83, quantizedStartStep: 9, quantizedEndStep: 10},
        {pitch: 82, quantizedStartStep: 10, quantizedEndStep: 11},
        {pitch: 81, quantizedStartStep: 11, quantizedEndStep: 12},
        {pitch: 80, quantizedStartStep: 12, quantizedEndStep: 13},
        {pitch: 79, quantizedStartStep: 13, quantizedEndStep: 14},
        {pitch: 78, quantizedStartStep: 14, quantizedEndStep: 15},
        {pitch: 77, quantizedStartStep: 15, quantizedEndStep: 16},
        {pitch: 76, quantizedStartStep: 16, quantizedEndStep: 17},
        {pitch: 75, quantizedStartStep: 17, quantizedEndStep: 18},
        {pitch: 74, quantizedStartStep: 18, quantizedEndStep: 19},
        {pitch: 73, quantizedStartStep: 19, quantizedEndStep: 20},
        {pitch: 74, quantizedStartStep: 20, quantizedEndStep: 21},
        {pitch: 73, quantizedStartStep: 21, quantizedEndStep: 22},
        {pitch: 72, quantizedStartStep: 22, quantizedEndStep: 23},
        {pitch: 71, quantizedStartStep: 23, quantizedEndStep: 24},
        {pitch: 72, quantizedStartStep: 24, quantizedEndStep: 25},
        {pitch: 71, quantizedStartStep: 25, quantizedEndStep: 26},
        {pitch: 70, quantizedStartStep: 26, quantizedEndStep: 27},
        {pitch: 69, quantizedStartStep: 27, quantizedEndStep: 28}, //
        {pitch: 68, quantizedStartStep: 28, quantizedEndStep: 29},
        {pitch: 67, quantizedStartStep: 29, quantizedEndStep: 30},
        {pitch: 66, quantizedStartStep: 30, quantizedEndStep: 31},
        {pitch: 65, quantizedStartStep: 31, quantizedEndStep: 32},
    ]};

var MEL55 = { notes: [
        {pitch: 64, quantizedStartStep: 0, quantizedEndStep: 1},
        {pitch: 63, quantizedStartStep: 1, quantizedEndStep: 2},
        {pitch: 62, quantizedStartStep: 2, quantizedEndStep: 3},
        {pitch: 61, quantizedStartStep: 3, quantizedEndStep: 4},
        // {pitch: 62, quantizedStartStep: 4, quantizedEndStep: 5},
        // {pitch: 61, quantizedStartStep: 5, quantizedEndStep: 6},
        // {pitch: 60, quantizedStartStep: 6, quantizedEndStep: 7},
        // {pitch: 59, quantizedStartStep: 7, quantizedEndStep: 8},
        {pitch: 60, quantizedStartStep: 8, quantizedEndStep: 9},
        {pitch: 59, quantizedStartStep: 9, quantizedEndStep: 10},
        {pitch: 58, quantizedStartStep: 10, quantizedEndStep: 11},
        {pitch: 57, quantizedStartStep: 11, quantizedEndStep: 12},
        {pitch: 56, quantizedStartStep: 12, quantizedEndStep: 13},
        {pitch: 55, quantizedStartStep: 13, quantizedEndStep: 14},
        {pitch: 54, quantizedStartStep: 14, quantizedEndStep: 15},
        {pitch: 53, quantizedStartStep: 15, quantizedEndStep: 16},
        {pitch: 52, quantizedStartStep: 16, quantizedEndStep: 17},
        {pitch: 51, quantizedStartStep: 17, quantizedEndStep: 18},
        {pitch: 50, quantizedStartStep: 18, quantizedEndStep: 19},
        {pitch: 49, quantizedStartStep: 19, quantizedEndStep: 20},
        // {pitch: 50, quantizedStartStep: 20, quantizedEndStep: 21},
        // {pitch: 49, quantizedStartStep: 21, quantizedEndStep: 22},
        // {pitch: 48, quantizedStartStep: 22, quantizedEndStep: 23},
        // {pitch: 47, quantizedStartStep: 23, quantizedEndStep: 24},
        {pitch: 48, quantizedStartStep: 24, quantizedEndStep: 25},
        {pitch: 47, quantizedStartStep: 25, quantizedEndStep: 26},
        {pitch: 46, quantizedStartStep: 26, quantizedEndStep: 27},
        {pitch: 45, quantizedStartStep: 27, quantizedEndStep: 28}, //
        {pitch: 44, quantizedStartStep: 28, quantizedEndStep: 29},
        {pitch: 43, quantizedStartStep: 29, quantizedEndStep: 30},
        {pitch: 42, quantizedStartStep: 30, quantizedEndStep: 31},
        {pitch: 41, quantizedStartStep: 31, quantizedEndStep: 32},
    ]};

var MEL6 = { notes: [ // 사계 - 겨울
        {pitch: 84, quantizedStartStep: 0, quantizedEndStep: 1},
        {pitch: 84, quantizedStartStep: 1, quantizedEndStep: 2},
        {pitch: 75, quantizedStartStep: 4, quantizedEndStep: 5},
        {pitch: 75 , quantizedStartStep: 5, quantizedEndStep: 6},
        {pitch: 84, quantizedStartStep: 8, quantizedEndStep: 9},
        {pitch: 84, quantizedStartStep: 9, quantizedEndStep: 10},
        {pitch: 75, quantizedStartStep: 12, quantizedEndStep: 13},
        {pitch: 75, quantizedStartStep: 13, quantizedEndStep: 14},  //
        {pitch: 84, quantizedStartStep: 16, quantizedEndStep: 17},
        {pitch: 82, quantizedStartStep: 17, quantizedEndStep: 18},
        {pitch: 80, quantizedStartStep: 18, quantizedEndStep: 19},
        {pitch: 79, quantizedStartStep: 19, quantizedEndStep: 20},
        {pitch: 77, quantizedStartStep: 20, quantizedEndStep: 21},
        {pitch: 75, quantizedStartStep: 21, quantizedEndStep: 22},
        {pitch: 74, quantizedStartStep: 22, quantizedEndStep: 23}, //
        {pitch: 84, quantizedStartStep: 24, quantizedEndStep: 25},
        {pitch: 82, quantizedStartStep: 25, quantizedEndStep: 26},
        {pitch: 80, quantizedStartStep: 26, quantizedEndStep: 27},
        {pitch: 79, quantizedStartStep: 27, quantizedEndStep: 28},
        {pitch: 77, quantizedStartStep: 28, quantizedEndStep: 29},
        {pitch: 75, quantizedStartStep: 29, quantizedEndStep: 30},
        {pitch: 74, quantizedStartStep: 30, quantizedEndStep: 31},
        {pitch: 72, quantizedStartStep: 31, quantizedEndStep: 32},
    ]};

var MEL66 = { notes: [
        {pitch: 79, quantizedStartStep: 1, quantizedEndStep: 2},
        {pitch: 79, quantizedStartStep: 2, quantizedEndStep: 3},
        {pitch: 72, quantizedStartStep: 6, quantizedEndStep: 7},
        {pitch: 72, quantizedStartStep: 7, quantizedEndStep: 8},
        {pitch: 79, quantizedStartStep: 10, quantizedEndStep: 11},
        {pitch: 79, quantizedStartStep: 11, quantizedEndStep: 12},
        {pitch: 72, quantizedStartStep: 14, quantizedEndStep: 15},
        {pitch: 72, quantizedStartStep: 15, quantizedEndStep: 16},
        {pitch: 72, quantizedStartStep: 23, quantizedEndStep: 24},
        {pitch: 72, quantizedStartStep: 24, quantizedEndStep: 25},
        {pitch: 70, quantizedStartStep: 25, quantizedEndStep: 26},
        {pitch: 68, quantizedStartStep: 26, quantizedEndStep: 27},
        {pitch: 67, quantizedStartStep: 27, quantizedEndStep: 28},
        {pitch: 65, quantizedStartStep: 28, quantizedEndStep: 29},
        {pitch: 63, quantizedStartStep: 29, quantizedEndStep: 30},
        {pitch: 62, quantizedStartStep: 30, quantizedEndStep: 31},
        {pitch: 60, quantizedStartStep: 31, quantizedEndStep: 32},
    ]};

var MELODY1 = MEL1;
var MELODY2 = MEL2;
var MELODY3 = MEL11;
var MELODY4 = MEL22;